name: Java CI with Maven (Backend)

on:
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Apply Spotless code formatting
      run: mvn com.diffplug.spotless:spotless-maven-plugin:check
    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml
