name: Deploy to Timperio Deployment Repository

on:
  push:
    branches:
      - master

jobs:
  merged_backend:
    uses: ./.github/workflows/merged_backend.yml

  deploy:
    needs:
      - merged_backend

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Get latest commit message
        id: get_commit_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Copy to deployment repo
        run: |
          git config --global user.name "joshydavid"
          git config --global user.email joshydavidang@outlook.sg
          APP_REPO_NAME=$(basename "$PWD")
          cd ..
          git clone https://x-access-token:${{ secrets.DEPLOY_BACKEND_PAT }}@github.com/joshydavid/timperio-deployment.git
          cd timeperio-deployment
          find . -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
          cd ../$APP_REPO_NAME
          rsync -av --exclude='.git' --exclude='.github' . ../timeperio-deployment/
          cd ../timeperio-deployment
          git add .
          git diff --staged --quiet || git commit -m "${{ steps.get_commit_message.outputs.commit_message }}"
          git push origin master --force || echo "No changes to push"
        env:
          DEPLOY_PAT: ${{ secrets.DEPLOY_BACKEND_PAT }}
